# Generated by Django 4.1.2 on 2022-11-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20210423_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='p_material',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Platinum', 'Platimnum'), ('Brass', 'Brass'), ('Bangles', 'Bangles'), ('Diamond', 'Diamond'), ('Pearl', 'Pearl'), ('Rose Gold', 'Rose Gold')], max_length=200),
        ),
    ]
